### ISSUE TITLE
How do I pull this library with composer

### ISSUE THREAD

**Issue by edwinmugendi** [kenguest/Services_Openstreetmap#6] opened 2015-04-04 08:44 UTC
Here is my composer.json

"repositories":
    [
        {
            "type": "vcs",
            "url": "git@github.com:kenguest/Services_Openstreetmap.git"
        }
    ],
    "require": {
        "pear/http_request2": "dev-trunk",
        "kenguest/services-openstreetmap": "V0.3.1"
    },
    
When I run composer update I get this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package kenguest/services-openstreetmap could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

What might be the problem and possible solution.
Thanks

**Comment by samdark** [comment] 2015-07-28 22:43
```
composer require kenguest/services-openstreetmap:~0.4.0
```

**Comment by kenguest** [comment] 2015-07-29 00:13
composer require kenguest/services-openstreetmap:dev-master should work now, as I relaxed some of the requirements to more up-to-date versions.

**Comment by kenguest** [comment] 2015-07-29 10:06
duplicate of issue #5

**Closed by kenguest** 2015-07-29 10:06 UTC
