### ISSUE TITLE
Composer installer

### ISSUE THREAD

**Issue by vitalyzhakov** [kenguest/Services_Openstreetmap#8] opened 2015-08-21 18:39 UTC
Hello!

Today I found your project.
But in installation on Ubuntu 14.04 I have problem
```bash
sudo pear install Services_OpenStreetMap-0.4.0
could not extract the package.xml file from "/build/php5-FncNNb/php5-5.5.9+dfsg/pear-build-download/Services_OpenStreetMap-0.4.0.tgz"
Download of "pear/Services_OpenStreetMap" succeeded, but it is not a valid package archive
```

I have solved this
`sudo pear install -Z http_request2`

Is it modern to produce full composer package and installation instructions for this on readme?

So, my project is based on Yii2, it uses composer install platform. You will have much more installations on shared hosting.

**Comment by kenguest** [comment] 2015-08-21 23:28
Duplicate of issue #5. Also please note that Ubuntu's support for PEAR is broken and logged at https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1434099, so to install any package via PEAR requires Archive_Tar to be constantly upgraded, via `sudo pear upgrade -Z Archive_Tar`, after any php upgrade.

**Closed by kenguest** 2015-08-21 23:28 UTC
